/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AbortView: typeof import('./src/components/AbortView.vue')['default']
    AlbumView: typeof import('./src/components/AlbumView.vue')['default']
    Author: typeof import('./src/components/lib/Author.vue')['default']
    Details: typeof import('./src/components/Details.vue')['default']
    Edit: typeof import('./src/components/Edit.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Home: typeof import('./src/components/NoteFrame/Home.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    IndexView: typeof import('./src/components/IndexView.vue')['default']
    Library: typeof import('./src/components/lib/Library.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    NotesView: typeof import('./src/components/NotesView.vue')['default']
    NoteVditorViews: typeof import('./src/components/NoteVditorViews/index.vue')['default']
    Outline: typeof import('./src/components/markdown/outline.vue')['default']
    Preview: typeof import('./src/components/markdown/preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/lib/Setting.vue')['default']
    ShowNoteView: typeof import('./src/components/NoteDetailViews/ShowNoteView.vue')['default']
    Tag: typeof import('./src/components/Tag/Tag.vue')['default']
    TagArray: typeof import('./src/components/lib/Tag-Array.vue')['default']
    Tags: typeof import('./src/components/lib/Tags.vue')['default']
    Tools: typeof import('./src/components/tools/index.vue')['default']
  }
}
